board/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    
]

bord/bord/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),

]

bord/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    
    # Create
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),

    # Delete
    path('<int:id>/delete/', views.delete, name='delete'),

    # Update
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),

    # Create
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    
    # Delete
    path('<int:id>/delete/', views.delete, name='delete'),

    # Update
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
]

bord/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

bord/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
# Create your views here.

def index(request):
    posts = Post.objects.all()

    context = {
        'posts': posts,
    }

    return render(request, 'index.html', context)


def detail(request, id):
    post = Post.objects.get(id=id)

    context = {
        'post': post,
    }

    return render(request, 'detail.html', context)

def new(request):
    return render(request, 'new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    post = Post(title=title, content=content)
    post.save()

    return redirect('posts:detail', id=post.id)


def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()

    return redirect('posts:index')

def edit(request, id):
    post = Post.objects.get(id=id)

    context = {
        'post': post,
    }

    return render(request, 'edit.html', context)


def update(request, id):
    title = request.POST.get('title')
    content = request.POST.get('content')

    post = Post.objects.get(id=id)
    post.title = title
    post.content = content
    post.save()

    return redirect('posts:detail', id=post.id)

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
# Create your views here.

def index(request):
    posts = Post.objects.all()

    context = {
        'posts': posts,
    }
    return render(request, 'index.html', context)

def detail(request, id):
    post = Post.objects.get(id=id)

    context = {
        'post': post,
    }

    return render(request, 'detail.html', context)


def new(request):
    return render(request, 'new.html')


def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    # post = Post()
    # post.title = title
    # post.content = content
    # post.save()

    post = Post(title=title, content=content)
    post.save()

    return redirect('posts:detail', id=post.id)


def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()

    return redirect('posts:index')

def edit(request, id):
    post = Post.objects.get(id=id)

    context = {
        'post': post,
    }

    return render(request, 'edit.html', context)


def update(request, id):
    # new data
    title = request.POST.get('title')
    content = request.POST.get('content')

    # old data
    post = Post.objects.get(id=id)
    post.title = title
    post.content = content
    post.save()

    return redirect('posts:detail', id=post.id)

bord/posts/templates/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="card mt-4">
        <div class="card-header">
            {{post.title}}
        </div>
        <div class="card-body">
            {{post.content}}
        </div>
        <div class="card-footer">
            <p>{{post.created_at}}</p>
            <a href="{% url 'posts:delete' id=post.id %}" class="btn btn-danger">delete</a>
            <a href="{% url 'posts:edit' id=post.id %}" class="btn btn-warning">edit</a>

        </div>
    </div>



{% endblock %}

bord/posts/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'posts:update' id=post.id %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="title" class="form-label">제목</label>
      <input type="text" class="formtitle-control" id="title" name="title" value="{{post.title}}">
     
    </div>
    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <!-- <input type="password" class="form-control" id="exampleInputPassword1"> -->
      <textarea class="form-control" name="content" id="content" cols="30" rows="10">{{post.content}}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>



{% endblock %}

bord/posts/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>제목</th>
                <th>상세보기</th>

            </tr>

        </thead>

        <tbody>
            {% for post in posts %}
                <tr>
                    <td>{{post.title}}</td>
                    <td><a href="{% url 'posts:detail' id=post.id %}">detail</a></td>

                </tr>

            {% endfor %}


            </tbody>

    </table>



{% endblock %}

bord/posts/templates/new.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'posts:create' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="title" class="form-label">제목</label>
      <input type="text" class="formtitle-control" id="title" name="title">
     
    </div>
    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <!-- <input type="password" class="form-control" id="exampleInputPassword1"> -->
      <textarea class="form-control" name="content" id="content" cols="30" rows="10"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>



{% endblock %}

bord/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'posts:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link"  href="{% url 'posts:new' %}">create</a>
              <a class="nav-link" href="#">Features</a>
              <a class="nav-link" href="#">Pricing</a>
              <a class="nav-link disabled">Disabled</a>
            </div>
          </div>
        </div>
    </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

posts/templates/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="card mt-4">
        <div class="card-header">
            {{post.title}}
        </div>
        <div class="card-body">
            {{post.content}}
        </div>
        <div class="card-footer">
            <p>{{post.created_at}}</p>
            <a href="{% url 'posts:delete' id=post.id %}" class="btn btn-danger">delete</a>
            <a href="{% url 'posts:edit' id=post.id %}" class="btn btn-warning">edit</a>
        </div>
    </div>


    

{% endblock %}

posts/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'posts:update' id=post.id %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="title" class="form-label">제목</label>
      <input type="text" class="form-control" id="title" name="title" value="{{post.title}}">

    </div>
    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <!-- <input type="password" class="form-control" id="exampleInputPassword1"> -->
    <textarea class="form-control" id="content" cols="30" rows="10" name="content">{{post.content}}</textarea>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

posts/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>제목</th>
                <th>상세보기</th>
            </tr>


        </thead>

        <tbody>
            {% for post in posts %}
                <tr>
                    <td>{{post.title}}</td>
                    <td><a href="{% url 'posts:detail' id=post.id %}">detail</a></td>
                </tr>

            {% endfor %}

        </tbody>
    </table>


{% endblock %}

posts/templates/new.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'posts:create' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="title" class="form-label">제목</label>
      <input type="text" class="form-control" id="title" name="title">

    </div>
    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <!-- <input type="password" class="form-control" id="exampleInputPassword1"> -->
    <textarea class="form-control" id="content" cols="30" rows="10" name="content"></textarea>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <!-- <a class="navbar-brand" href="/posts/">Home</a> -->
          <!-- url 'app_name:name' -->
          <a class="navbar-brand" href="{% url 'posts:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'posts:new' %}">create</a>
              <a class="nav-link" href="#">Features</a>
              <a class="nav-link" href="#">Pricing</a>
              <a class="nav-link disabled" >Disabled</a>
            </div>
          </div>
        </div>
    </nav>
    
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>